# Generated by Django 3.0.5 on 2020-04-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateTimeField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('zipcode', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('address_detail', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
