# Generated by Django 3.0.5 on 2020-04-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='business_time',
            field=models.CharField(max_length=100),
        ),
    ]
