# Generated by Django 3.0.5 on 2020-04-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20200428_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='interior',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
